name: objeto_rastreado_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  loading_animation_widget: ^1.2.0+4
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  js: ^0.6.6

flutter:
  uses-material-design: true

routes: {
  '/login': (context) => const LoginScreen(),
  '/home': (context) => const HomeScreen(),
  '/add_object': (context) => const AddObjectScreen(),
  '/object_details': (context) => const ObjectDetailsScreen(),
  '/report_stolen': (context) => const ReportStolenObjectScreen(),
  '/stolen_objects': (context) => const StolenObjectsScreen(),
}
